site_name: QueryWeaver Documentation
site_url: https://FabianAltermann.github.io/queryweaver/

theme:
  name: "material"
  palette:
    primary: "teal"

nav:
  - Getting Started: index.md
  - Install: install.md
  - Full Example: example.md
