name: Example

on: push

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.1"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: "Install dependencies"
        run: |
          make install

      - name: "Linting and formatting"
        run: |
          make check

      - name: "Run tests"
        run: |
          make tests
